# ANIMAL_INS 
# PK : ANIMAL_ID
# ANIMAL_OUTS
# PK : ANIMAL_OUTS

SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID ASC;