-- SELECT 
--     TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, 
--     TO_CHAR(O.SALES_DATE, 'MM') AS MONTH, 
--     U.GENDER,
--     COUNT(DISTINCT O.USER_ID) AS USERS
-- FROM ONLINE_SALE O, USER_INFO U
-- WHERE O.USER_ID = U.USER_ID
-- AND U.GENDER IS NOT NULL
-- GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
-- ORDER BY YEAR, MONTH, U.GENDER

SELECT
    EXTRACT(YEAR FROM SALES_DATE) YEAR,
    EXTRACT(MONTH FROM SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO I, ONLINE_SALE O
WHERE I.USER_ID = O.USER_ID
AND GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER
ORDER BY
    YEAR, MONTH, GENDER