SELECT DISTINCT *
FROM (
SELECT CAR_ID, CAR_TYPE, 30 * ROUND(DAILY_FEE - (DAILY_FEE * DISCOUNT),0) AS FEE
FROM (
SELECT 
    CAR_ID, CAR_TYPE, DAILY_FEE,
    CASE WHEN CAR_TYPE = '세단' THEN
    (SELECT DISCOUNT_RATE/100
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상'
     AND CAR_TYPE = '세단')
    WHEN CAR_TYPE = 'SUV' THEN
    (SELECT DISCOUNT_RATE/100
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상'
     AND CAR_TYPE = 'SUV')
    END AS DISCOUNT
FROM (
    SELECT 
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        H.START_DATE,
        H.END_DATE
    FROM  
        CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE
        C.CAR_ID = H.CAR_ID
    AND
        C.CAR_TYPE IN ('세단', 'SUV')
    AND 
        C.CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE EXTRACT(MONTH FROM START_DATE) <= 10
                            AND EXTRACT(YEAR FROM END_DATE) > 2022 
                        OR EXTRACT(MONTH FROM START_DATE) <= 10
                            AND EXTRACT(MONTH FROM END_DATE) >= 11
                        OR EXTRACT(MONTH FROM START_DATE) = 11
                            AND EXTRACT(MONTH FROM END_DATE) = 11)
        )
    )
)
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC, CAR_TYPE ASC, CAR_ID DESC;