-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME = 'Milk'
-- INTERSECT
-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME = 'Yogurt'

-- SELECT CART_ID
-- FROM CART_PRODUCTS
-- WHERE NAME IN ('Milk', 'Yogurt')
-- GROUP BY CART_ID
-- HAVING COUNT(DISTINCT NAME) = 2
-- ORDER BY CART_ID;

SELECT DISTINCT CP1.CART_ID
FROM CART_PRODUCTS CP1
WHERE CP1.NAME = 'Milk'
AND EXISTS (
    SELECT 1
    FROM CART_PRODUCTS CP2
    WHERE CP2.CART_ID = CP1.CART_ID
    AND CP2.NAME = 'Yogurt'
)
ORDER BY CART_ID ASC;