
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE)
                                 FROM REST_INFO)
ORDER BY FOOD_TYPE DESC;
                                
