-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
SELECT
    REST_ID,
    REST_NAME,
    FAVORITES,
    FOOD_TYPE,
    ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE
                    ORDER BY FAVORITES DESC) AS RK
FROM REST_INFO
    )
WHERE RK = 1
ORDER BY FOOD_TYPE DESC;
