SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE,
PRODUCT_ID,USER_ID,SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE like '2022-03%'
UNION ALL # UNION ALL 하면 중복값을 제거 하지 않고 보여줌
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE,
PRODUCT_ID,null as PRODUCT_ID,SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE like '2022-03%'
order by SALES_DATE,PRODUCT_ID,USER_ID;