WITH TBL AS (SELECT 
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT 
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
UNION DISTINCT
SELECT 
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID, 
    NULL USER_ID, 
    SALES_AMOUNT 
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03')

SELECT * 
FROM TBL 
ORDER BY TBL.SALES_DATE, TBL.PRODUCT_ID, TBL.USER_ID