-- 코드를 입력하세요

SELECT F.FLAVOR
FROM ICECREAM_INFO I, 
    (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        WHERE TOTAL_ORDER >= 3000
    ) F
WHERE I.FLAVOR = F.FLAVOR
AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;