-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(CR.START_DATE, 'MM')) AS MONTH , CR.CAR_ID , COUNT(*) AS RECORDS 
FROM ( SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10' 
      GROUP BY CAR_ID 
      HAVING COUNT(*) >= 5 ) TEMP JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CR 
ON TEMP.CAR_ID = CR.CAR_ID 
WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10' 
GROUP BY TO_CHAR(CR.START_DATE, 'MM'), CR.CAR_ID 
ORDER BY MONTH, CAR_ID DESC;