-- 코드를 입력하세요
SELECT
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM (
        SELECT 
            CAR_ID,
            START_DATE,
            COUNT(*) OVER(PARTITION BY CAR_ID) AS CNT
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE EXTRACT(MONTH FROM START_DATE) IN (8,9,10)
    )
WHERE CNT >= 5
GROUP BY 
    EXTRACT(MONTH FROM START_DATE),
    CAR_ID
ORDER BY
    MONTH ASC,
    CAR_ID DESC;
