SELECT MONTH, CAR_ID, RECORDS
FROM (SELECT DISTINCT MONTH(START_DATE) AS MONTH, CAR_ID, 
      COUNT(*) OVER(PARTITION BY MONTH(START_DATE), CAR_ID) AS RECORDS, #월별 자동차별 대여 횟수
      COUNT(*) OVER(PARTITION BY CAR_ID) AS CNT #자동차별 대여 횟수
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10) TB
WHERE CNT >= 5
ORDER BY MONTH ASC, CAR_ID DESC;