-- 서브쿼리
-- SELECT *
-- FROM FOOD_PRODUCT
-- WHERE PRICE = (SELECT MAX(PRICE)
--               FROM FOOD_PRODUCT)

-- SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
-- FROM (
-- SELECT
--     PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE,
--     RANK() OVER(ORDER BY PRICE DESC) AS RANK
-- FROM FOOD_PRODUCT
--     )
-- WHERE RANK = 1

SELECT *
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
FETCH FIRST 1 ROWS ONLY;