SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM (
SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE,
    RANK() OVER(ORDER BY PRICE DESC) AS RANK
FROM FOOD_PRODUCT
    ) 
WHERE RANK = 1