-- 코드를 입력하세요
WITH A AS 
(SELECT TO_NUMBER(ROWNUM-1) AS HOUR
FROM ANIMAL_OUTS
WHERE TO_NUMBER(ROWNUM-1) <= 23),
B AS
(SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR
     , COUNT(*) CNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24'))
SELECT A.HOUR, NVL(CNT,'0') AS COUNT
FROM A, B
WHERE A.HOUR = B.HOUR(+)
ORDER BY A.HOUR