-- 코드를 입력하세요
SELECT A.HOUR, IFNULL(B.CNT, 0) AS COUNT
FROM (
    SELECT ROWNUM - 1 AS HOUR
    FROM (
        SELECT ROW_NUMBER() OVER(ORDER BY ANIMAL_ID) AS ROWNUM
        FROM ANIMAL_OUTS
        ) TBL_1
    WHERE ROWNUM < 25
    ) A LEFT JOIN (
        SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS CNT
        FROM ANIMAL_OUTS
        GROUP BY HOUR(DATETIME)
    ) B
ON A.HOUR = B.HOUR
ORDER BY A.HOUR ASC;