-- 코드를 입력하세요
SELECT 
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    I.GENDER,
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO I, ONLINE_SALE O
WHERE I.USER_ID = O.USER_ID
AND I.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM O.SALES_DATE),
    EXTRACT(MONTH FROM O.SALES_DATE),
    I.GENDER
ORDER BY
    YEAR,
    MONTH,
    I.GENDER
;
