-- 코드를 입력하세요
SELECT FLAVOR
FROM(
SELECT F.FLAVOR, SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) AS TOTAL_ORDER,
    RANK() OVER(ORDER BY SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) DESC) AS RN
FROM FIRST_HALF F, (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR
    ) J
WHERE F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
    )
WHERE RN<=3