SELECT FLAVOR
FROM (
SELECT H.FLAVOR, SUM(H.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF H, 
    (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J
WHERE H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
    )
ORDER BY TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY