-- -- SELECT NAME, DATETIME
-- FROM ANIMAL_INS
-- WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
--                        FROM ANIMAL_OUTS)
-- ORDER BY DATETIME ASC
-- FETCH FIRST 3 ROWS ONLY;
SELECT NAME, DATETIME
FROM ( 
        SELECT I.NAME, I.DATETIME
        FROM ANIMAL_INS I, ANIMAL_OUTS O
        WHERE I.ANIMAL_ID = O.ANIMAL_ID(+)
        AND O.ANIMAL_ID IS NULL
        ORDER BY I.DATETIME ASC
    )
WHERE ROWNUM <= 3;


