-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(RENTAL_PERIOD), 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, END_DATE-START_DATE+1 AS RENTAL_PERIOD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
GROUP BY CAR_ID
HAVING AVG(RENTAL_PERIOD) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
;