-- 코드를 입력하세요
-- SELECT
--     PRICE_GROUP,
--     COUNT(PRODUCT_ID) AS PRODUCTS
-- FROM(
--     SELECT
--         PRODUCT_ID,
--         ROUND(PRICE/10000, 0)*10000 AS PRICE_GROUP
--     FROM PRODUCT
--     )
-- GROUP BY PRICE_GROUP
-- ORDER BY PRICE_GROUP

SELECT
    TRUNC(PRICE, -4) AS PRICE_GROUP, 
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNC(PRICE, -4)
ORDER BY PRICE_GROUP ASC
