-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, C.CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A, (
SELECT B.AUTHOR_ID, B.CATEGORY, B.PRICE*BS.SALES AS TOTAL_SALES
FROM BOOK_SALES BS, BOOK B
WHERE BS.BOOK_ID = B.BOOK_ID
AND TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
    ) C
WHERE A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, C.CATEGORY
ORDER BY A.AUTHOR_ID, C.CATEGORY DESC;