-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT 
        FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER,
        ROW_NUMBER() OVER(ORDER BY SUM(TOTAL_ORDER) DESC) AS RN 
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
    ) 
    GROUP BY FLAVOR
)
WHERE RN <= 3
;
