-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D, (
    SELECT *
    FROM APPOINTMENT
    WHERE APNT_CNCL_YN = 'N'
    AND TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
    AND MCDP_CD = 'CS'
) A
WHERE P.PT_NO = A.PT_NO
AND D.DR_ID = A.MDDR_ID
ORDER BY APNT_YMD ASC
;