# CAR_RENTAL_COMPANY_CAR
# PK : car_id
# CAR_RENTAL_COMPANY_RENTAL_HISTORY
# PK : history_id
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# PK : plan_id

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭"

# SELECT HISTORY_ID, ROUND((DAILY_FEE - DAILY_FEE * (DISCOUNT_RATE/100))*(DATEDIFF(END_DATE,START_DATE)+1),0) AS FEE
# FROM
# (SELECT 
#     DAILY_FEE,
#     CAR_TYPE,
#     B.HISTORY_ID, 
#     START_DATE,
#     END_DATE,
#     A.CAR_ID, 
# CASE WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN '7일 이상'
#     WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '30일 이상'
#     WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
#     ELSE '7일 미만' END AS 'DURATION_TYPE'
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭") DIFF JOIN
# (SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) DIS ON
# DIFF.DURATION_TYPE = DIS.DURATION_TYPE
# ORDER BY FEE DESC, HISTORY_ID DESC;


# SELECT 
#     CASE WHEN 대여기간 >= 90 THEN '90일 이상'
#     WHEN 대여기간 >= 30 THEN '30일 이상'
#     WHEN 대여기간 >= 7 THEN '7일 이상'
#     ELSE '7일 미만' END AS '구분'
# FROM(
# SELECT A.CAR_ID, DAILY_FEE, HISTORY_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)+1 AS '대여기간'
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭"
# ORDER BY A.CAR_ID, B.HISTORY_ID
#     ) TBL

SELECT 
    HISTORY_ID, 
    ROUND(RENTAL_PERIOD * 할인적용,0) AS FEE
FROM (
SELECT 
    HISTORY_ID, 
    DAILY_FEE - (DAILY_FEE * (DC_RATE/100)) AS 할인적용, 
    RENTAL_PERIOD
FROM (
SELECT 
    HISTORY_ID, 
    DAILY_FEE, 
    RENTAL_PERIOD, 
    CASE WHEN 구분 = '90일 이상' THEN (SELECT DISCOUNT_RATE
                                     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                     WHERE CAR_TYPE = "트럭"
                                     AND DURATION_TYPE = "90일 이상")
    WHEN 구분 = '30일 이상' THEN (SELECT DISCOUNT_RATE
                                     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                     WHERE CAR_TYPE = "트럭"
                                     AND DURATION_TYPE = "30일 이상")
    WHEN 구분 = '7일 이상' THEN (SELECT DISCOUNT_RATE
                                     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                     WHERE CAR_TYPE = "트럭"
                                     AND DURATION_TYPE = "7일 이상")
    ELSE 0.00 END AS 'DC_RATE'
FROM (
SELECT HISTORY_ID, DAILY_FEE, RENTAL_PERIOD,
    CASE WHEN RENTAL_PERIOD >= 90 THEN '90일 이상'
    WHEN RENTAL_PERIOD >= 30 THEN '30일 이상'
    WHEN RENTAL_PERIOD >= 7 THEN '7일 이상'
    ELSE '7일 미만' END AS '구분'
FROM(
SELECT 
    A.CAR_ID, 
    DAILY_FEE, 
    HISTORY_ID, 
    START_DATE, 
    END_DATE, 
    DATEDIFF(END_DATE,START_DATE)+1 AS 'RENTAL_PERIOD'
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
    ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"
    ) TBL_1 ) TBL_2 ) TBL_3 ) TBL_4
ORDER BY FEE DESC, HISTORY_ID DESC