# CAR_RENTAL_COMPANY_CAR
# PK : car_id
# CAR_RENTAL_COMPANY_RENTAL_HISTORY
# PK : history_id
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# PK : plan_id

# CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 
# 자동차 종류가 '트럭'인 자동차의 
# 대여 기록에 대해서 
# 대여 기록 별로 
# 대여 금액(컬럼명: FEE)을 구하여 
# 대여 기록 ID와 대여 금액 리스트를 출력.
# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭"

# SELECT HISTORY_ID, ROUND((DAILY_FEE - DAILY_FEE * (DISCOUNT_RATE/100))*(DATEDIFF(END_DATE,START_DATE)+1),0) AS FEE
# FROM
# (SELECT 
#     DAILY_FEE,
#     CAR_TYPE,
#     B.HISTORY_ID, 
#     START_DATE,
#     END_DATE,
#     A.CAR_ID, 
# CASE WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN '7일 이상'
#     WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '30일 이상'
#     WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
#     ELSE '7일 미만' END AS 'DURATION_TYPE'
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭") DIFF JOIN
# (SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) DIS ON
# DIFF.DURATION_TYPE = DIS.DURATION_TYPE
# ORDER BY FEE DESC, HISTORY_ID DESC;


# SELECT 
#     CASE WHEN 대여기간 >= 90 THEN '90일 이상'
#     WHEN 대여기간 >= 30 THEN '30일 이상'
#     WHEN 대여기간 >= 7 THEN '7일 이상'
#     ELSE '7일 미만' END AS '구분'
# FROM(
# SELECT A.CAR_ID, DAILY_FEE, HISTORY_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)+1 AS '대여기간'
# FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE = "트럭"
# ORDER BY A.CAR_ID, B.HISTORY_ID
#     ) TBL

SELECT HISTORY_ID, ROUND(대여기간 * 할인적용,0) AS FEE
FROM (
SELECT HISTORY_ID, DAILY_FEE - (DAILY_FEE * 할인율) AS 할인적용, 대여기간
FROM (
SELECT HISTORY_ID, DAILY_FEE, 대여기간, 
    CASE WHEN 구분 = '90일 이상' THEN 0.15
    WHEN 구분 = '30일 이상' THEN 0.08
    WHEN 구분 = '7일 이상' THEN 0.05
    ELSE 0.00 END AS '할인율'
FROM (
SELECT HISTORY_ID, DAILY_FEE, 대여기간,
    CASE WHEN 대여기간 >= 90 THEN '90일 이상'
    WHEN 대여기간 >= 30 THEN '30일 이상'
    WHEN 대여기간 >= 7 THEN '7일 이상'
    ELSE '7일 미만' END AS '구분'
FROM(
SELECT A.CAR_ID, DAILY_FEE, HISTORY_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)+1 AS '대여기간'
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"
    ) TBL_1 ) TBL_2 ) TBL_3 ) TBL_4
ORDER BY FEE DESC, HISTORY_ID DESC;

                                     