-- 코드를 입력하세요
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(총매출) AS TOTAL_SALES
FROM (
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE * O.AMOUNT AS 총매출
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
AND TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
    )
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY 
    TOTAL_SALES DESC, PRODUCT_ID ASC;
