-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM (
    SELECT 
        MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE,
        RANK() OVER(ORDER BY CNT DESC) AS RN
    FROM MEMBER_PROFILE M, (
        SELECT 
            MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, 
            COUNT(REVIEW_ID) OVER(PARTITION BY MEMBER_ID) AS CNT
        FROM REST_REVIEW
    ) R
    WHERE M.MEMBER_ID = R.MEMBER_ID
)
WHERE RN = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT
;