SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM 
(SELECT A.*, PT_NAME
FROM APPOINTMENT A JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%'
AND APNT_CNCL_YN = 'N') AP JOIN 
(SELECT DR_ID, DR_NAME
FROM DOCTOR
WHERE MCDP_CD = 'CS') D ON AP.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC;
