SELECT 
    I.*, 
    ROUND(R.AVG_SCORE, 2) AS SCORE
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
    ) I, (
        SELECT REST_ID, AVG(REVIEW_SCORE) AS AVG_SCORE
        FROM REST_REVIEW
        GROUP BY REST_ID
    ) R 
WHERE I.REST_ID = R.REST_ID
ORDER BY 
    SCORE DESC,
    FAVORITES DESC
;


