SELECT DISTINCT 
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
    ROUND(AVG(REVIEW_SCORE) OVER(PARTITION BY R.REST_ID), 2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID
AND I.ADDRESS LIKE '서울%'
ORDER BY 
    SCORE DESC,
    FAVORITES DESC;