-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM (
    SELECT *
    FROM BOOK
    WHERE CATEGORY = '경제'
    ) B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY B.PUBLISHED_DATE ASC
;